apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-model-repo
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/model_repo/yolov8n_car"