apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: vae-0.x
  namespace: modelmesh-serving
spec:
  supportedModelFormats:
    - name: vae
      version: "1"
      autoSelect: true
  multiModel: true
  storageHelper:
    disabled: false
  replicas: 1
  grpcEndpoint: "port:8085"
  grpcDataEndpoint: "port:8001"
  containers:
    - name: mlserver
      image: fullstackdatascience/intrusion-detection-mm:0.0.20
      env:
        - name: MLSERVER_MODELS_DIR
          value: "/models/_mlserver_models/"
        - name: MLSERVER_GRPC_PORT
          value: "8001"
        - name: MLSERVER_HTTP_PORT
          value: "8002"
        - name: MLSERVER_LOAD_MODELS_AT_STARTUP
          value: "false"
        - name: MLSERVER_MODEL_NAME
          value: dummy-model
        # listen only on localhost
        - name: MLSERVER_HOST
          value: 127.0.0.1
        - name: MLSERVER_DEBUG
          value: "true"
        - name: MLSERVER_MODEL_PARALLEL_WORKERS
          value: "0"
      resources:
        limits:
          cpu: "2"
          memory: 1Gi
        requests:
          cpu: 500m
          memory: 1Gi
  builtInAdapter:
    serverType: mlserver
    runtimeManagementPort: 8001
    memBufferBytes: -134217728
    modelLoadingTimeoutMillis: 90000